---
title: 'RNAmodR: AlkAnilineSeq'
author: "Felix G.M. Ernst"
date: "`r Sys.Date()`"
abstract: >
  detection of m7G, m3C and D modification by AlkAnilineSeq
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
    df_print: paged
vignette: >
  %\VignetteIndexEntry{RNAmodR.AlkAnilineSeq}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown(css.files = c('custom.css'))
```

# Introduction









```{r, echo = FALSE}
suppressPackageStartupMessages({
  library(rtracklayer)
  library(Rsamtools)
  library(GenomicFeatures)
  library(RNAmodR.AlkAnilineSeq)
})
```
```{r, eval = FALSE}
library(rtracklayer)
library(Rsamtools)
library(GenomicFeatures)
library(RNAmodR.AlkAnilineSeq)
```

# Example workflow

Loading files
```{r}
annotation <- GFF3File(system.file("extdata","example_AAS.gff3" ,package = "RNAmodR.Data"))
sequences <- FaFile(system.file("extdata","example_AAS.fasta" ,package = "RNAmodR.Data"))
files <- list("BY4741" = c(treated = system.file("extdata","example_wt_1.bam" ,package = "RNAmodR.Data"),
                           treated = system.file("extdata","example_wt_2.bam" ,package = "RNAmodR.Data"),
                           treated = system.file("extdata","example_wt_3.bam" ,package = "RNAmodR.Data")),
              "BY4741 Bud23del" = c(treated = system.file("extdata","example_Bud23_1.bam" ,package = "RNAmodR.Data"),
                                    treated = system.file("extdata","example_Bud23_2.bam" ,package = "RNAmodR.Data")),
              "BY4741 Trm8del" = c(treated = system.file("extdata","example_Trm8_1.bam" ,package = "RNAmodR.Data"),
                                   treated = system.file("extdata","example_Trm8_2.bam" ,package = "RNAmodR.Data")))
```

Analysis of data

```{r}
msaas <- ModSetAlkAnilineSeq(files, annotation = annotation, sequences = sequences)
```

# Visualizing the results

```{r}

```

Heatmap

```{r}

```

sequence specific result

```{r}

```

# Session info

```{r, sessioninfo}
sessioninfo::session_info()
```

# References
